ui:
  title: "BCN Status | Banua Cloud"
  header: "Banua Cloud"
  description: "Monitor status layanan Banua Cloud secara real-time"
  dashboard-heading: "Status Layanan"
  dashboard-subheading: "Monitor layanan Banua Cloud"
  logo: "/img/logo-bcn.png"
  link: "https://banuacloud.id"
  favicon:
    default: "/img/logo-bcn.png"
    size16x16: "/img/logo-bcn.png"
    size32x32: "/img/logo-bcn.png"
  default-sort-by: group
  dark-mode: false

security:
  basic:
    username: "admin"
    password-bcrypt-base64: "JDJhJDEwJGZCTEY1c0NNWW5tZ210bjRHVi9Oa2V2OTdQVnBnM1Rsc3ZzT3JNdG5aS094eFhWS1gxdFpt"

endpoints:
  # Kominfo Servers
  - name: Server Kominfo 01
    group: Kominfo
    url: "icmp://157.15.123.19"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Server Kominfo 02
    group: Kominfo
    url: "icmp://157.15.123.20"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Server Kominfo 03
    group: Kominfo
    url: "icmp://157.15.123.21"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Server Kominfo 04
    group: Kominfo
    url: "icmp://157.15.123.23"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  # Banua Cloud Servers
  - name: Reverse Proxy BCN
    group: Banua Cloud
    url: "icmp://157.15.123.18"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: ACS Banuacloud
    group: Banua Cloud
    url: "icmp://157.15.123.26"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Hosting Banuacloud
    group: Banua Cloud
    url: "icmp://157.15.123.24"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Pterodactyl
    group: Banua Cloud
    url: "icmp://157.15.123.25"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
